<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="LearningAndDevelopment"
           tests="7"
           failures="2"
           errors="0"
           skipped="0"
           time="1.663">
  <properties />
            <testcase name="editProgramWithValidDetails" time="0.792" classname="com.jio.test.LearningAndDevelopment.EditProgramTest">
                <failure type="java.lang.AssertionError"
                  message="The following asserts failed:
	FAILED! API did not respond with status 200 expected [200] but found [404],
	Failed! UnExpected error code:::::404 expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: The following asserts failed:
	FAILED! API did not respond with status 200 expected [200] but found [404],
	Failed! UnExpected error code:::::404 expected [true] but found [false]
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
  com.jio.apiservice.LearningAndDevelopment.EditProgramService.editProgramWithValidDetails(EditProgramService.java:62)
  com.jio.test.LearningAndDevelopment.EditProgramTest.editProgramWithValidDetails(EditProgramTest.java:13)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:566)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  org.testng.TestRunner.publicRun(TestRunner.java:774)
  org.testng.TestRunner.run(TestRunner.java:624)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
  org.testng.SuiteRunner.publicRun(SuiteRunner.java:312)
  org.testng.SuiteRunner.run(SuiteRunner.java:261)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
  org.testng.TestNG.run(TestNG.java:1024)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
      </failure>

          </testcase>
            <testcase name="editProgramWithoutProgramTitle" time="0.178" classname="com.jio.test.LearningAndDevelopment.EditProgramTest">
                <failure type="java.lang.AssertionError"
                  message="The following asserts failed:
	FAILED! API did not respond with status 200 expected [200] but found [404],
	Failed! UnExpected error code:::::404 expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: The following asserts failed:
	FAILED! API did not respond with status 200 expected [200] but found [404],
	Failed! UnExpected error code:::::404 expected [true] but found [false]
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
  com.jio.apiservice.LearningAndDevelopment.EditProgramService.editProgramWithoutProgramTitle(EditProgramService.java:85)
  com.jio.test.LearningAndDevelopment.EditProgramTest.editProgramWithoutProgramTitle(EditProgramTest.java:23)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:566)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  org.testng.TestRunner.publicRun(TestRunner.java:774)
  org.testng.TestRunner.run(TestRunner.java:624)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
  org.testng.SuiteRunner.publicRun(SuiteRunner.java:312)
  org.testng.SuiteRunner.run(SuiteRunner.java:261)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
  org.testng.TestNG.run(TestNG.java:1024)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="editProgramWithoutDescriptionField" time="0.140" classname="com.jio.test.LearningAndDevelopment.EditProgramTest" />
                <testcase name="editProgramWithoutSkillId" time="0.128" classname="com.jio.test.LearningAndDevelopment.EditProgramTest" />
                <testcase name="editProgramWithoutRoleId" time="0.145" classname="com.jio.test.LearningAndDevelopment.EditProgramTest" />
                <testcase name="editProgramWithoutCourse" time="0.142" classname="com.jio.test.LearningAndDevelopment.EditProgramTest" />
                <testcase name="editProgramWitNonSequential" time="0.138" classname="com.jio.test.LearningAndDevelopment.EditProgramTest" />
      
</testsuite>
